name: Complete Step 2

on:
  workflow_dispatch:
    description: 'Run this after completing Step 2 (Adding Custom Fields)'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check current step
        id: check_step
        run: |
          current_step=$(grep -o "<!-- STEP: [0-9]\+ -->" README.md | sed -n 's/<!-- STEP: \([0-9]\+\) -->/\1/p' || echo "0")
          echo "CURRENT_STEP=$current_step" >> $GITHUB_ENV
          echo "Current step: $current_step"

      - name: Update README to step 3
        if: ${{ env.CURRENT_STEP == '2' }}
        run: |
          cp steps/step3.md README.md
          
          git config --local user.email "github-actions[bot]@user